apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
  nodeSelector:
    gpu: "false"  # Only schedule on nodes with gpu=false label
