apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
  namespace:  mem-testing
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "1G"
      limits:
        memory: "2G"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]